package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelInteraccionCaso generated by hbm2java
 */
@Entity
@Table(name = "cel_interaccion_caso", catalog = "seguimiento_alumnos")
public class CelInteraccionCaso implements java.io.Serializable {

	private Long casId;
	private String casObservacionesGrales;
	private long aluId;
	private Date audFechaIns;
	private Date audFechaUpd;
	private String audUsrIns;
	private String audUsrUpd;

	public CelInteraccionCaso() {
	}

	public CelInteraccionCaso(long aluId, Date audFechaIns, Date audFechaUpd,
			String audUsrIns, String audUsrUpd) {
		this.aluId = aluId;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
	}

	public CelInteraccionCaso(String casObservacionesGrales, long aluId,
			Date audFechaIns, Date audFechaUpd, String audUsrIns,
			String audUsrUpd) {
		this.casObservacionesGrales = casObservacionesGrales;
		this.aluId = aluId;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "CAS_ID", unique = true, nullable = false)
	public Long getCasId() {
		return this.casId;
	}

	public void setCasId(Long casId) {
		this.casId = casId;
	}

	@Column(name = "CAS_OBSERVACIONES_GRALES", length = 250)
	public String getCasObservacionesGrales() {
		return this.casObservacionesGrales;
	}

	public void setCasObservacionesGrales(String casObservacionesGrales) {
		this.casObservacionesGrales = casObservacionesGrales;
	}

	@Column(name = "ALU_ID", nullable = false)
	public long getAluId() {
		return this.aluId;
	}

	public void setAluId(long aluId) {
		this.aluId = aluId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_INS", nullable = false, length = 19)
	public Date getAudFechaIns() {
		return this.audFechaIns;
	}

	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_UPD", nullable = false, length = 19)
	public Date getAudFechaUpd() {
		return this.audFechaUpd;
	}

	public void setAudFechaUpd(Date audFechaUpd) {
		this.audFechaUpd = audFechaUpd;
	}

	@Column(name = "AUD_USR_INS", nullable = false, length = 250)
	public String getAudUsrIns() {
		return this.audUsrIns;
	}

	public void setAudUsrIns(String audUsrIns) {
		this.audUsrIns = audUsrIns;
	}

	@Column(name = "AUD_USR_UPD", nullable = false, length = 250)
	public String getAudUsrUpd() {
		return this.audUsrUpd;
	}

	public void setAudUsrUpd(String audUsrUpd) {
		this.audUsrUpd = audUsrUpd;
	}

}
