package ar.com.celia.seguimiento_alumnos.domain;

// Generated 06/04/2014 19:30:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VwIndicadoresAlumnos generated by hbm2java
 */
@Entity
@Table(name = "vw_indicadores_alumnos", schema = "seguimiento_alumnos")
public class VwIndicadoresAlumnos implements java.io.Serializable {

	private Long inaId;
	private VwAlumnosActivos vwAlumnosActivos;
	private Long idIndicador;
	private String nombreIndicador;
	private String descIndicador;
	private Long valorIndicador;
	

	//private String informacionAdicional;
	
	@Id
	@Column(name = "ina_id", nullable = false)
	public Long getInaId() {
		return this.inaId;
	}

	public void setInaId(Long inaId) {
		this.inaId = inaId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_id", nullable = false)
	public VwAlumnosActivos getVwAlumnosActivos() {
		return vwAlumnosActivos;
	}
	
	
	public void setVwAlumnosActivos(VwAlumnosActivos vwAlumnosActivos) {
		this.vwAlumnosActivos = vwAlumnosActivos;
	}

	@Column(name = "id_indicador", nullable = false, length = 1)
	public Long getIdIndicador() {
		return idIndicador;
	}
	
	public void setIdIndicador(Long idIndicador) {
		this.idIndicador = idIndicador;
	}

	@Column(name = "nombre_indicador", nullable = false, length = 250)
	public String getNombreIndicador() {
		return nombreIndicador;
	}
	
	public void setNombreIndicador(String nombreIndicador) {
		this.nombreIndicador = nombreIndicador;
	}
	
	@Column(name = "desc_indicador", nullable = false, length = 250)
	public String getDescIndicador() {
		return this.descIndicador;
	}

	public void setDescIndicador(String descIndicador) {
		this.descIndicador = descIndicador;
	}

	@Column(name = "valor_indicador", nullable = false)
	public Long getValorIndicador() {
		return this.valorIndicador;
	}

	public void setValorIndicador(Long valorIndicador) {
		this.valorIndicador = valorIndicador;
	}
	
	/*@Column(name = "informacion_adicional", nullable = true, length = 4000)
	public String getInformacionAdicional() {
		return informacionAdicional;
	}
	
	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}*/	
	
}
