package ar.com.celia.seguimiento_alumnos.domain;

// Generated 06/04/2014 19:30:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VwIndicadoresAlumnos generated by hbm2java
 */
@Entity
@Table(name = "vw_indicadores_alumnos", catalog = "celiacie_moodle2")
public class VwIndicadoresAlumnos implements java.io.Serializable {

	private Long id;
	private VwAlumnosActivos vwAlumnosActivos;
	private String codigoIndicador;
	private String descIndicador;
	private Long valorIndicador;
	
	
	@Id
	@Column(name = "id", nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_id", nullable = false)
	public VwAlumnosActivos getVwAlumnosActivos() {
		return vwAlumnosActivos;
	}
	
	
	public void setVwAlumnosActivos(VwAlumnosActivos vwAlumnosActivos) {
		this.vwAlumnosActivos = vwAlumnosActivos;
	}

	

	@Column(name = "codigo_indicador", nullable = false, length = 1)
	public String getCodigoIndicador() {
		return this.codigoIndicador;
	}

	public void setCodigoIndicador(String codigoIndicador) {
		this.codigoIndicador = codigoIndicador;
	}

	@Column(name = "desc_indicador", nullable = false, length = 25)
	public String getDescIndicador() {
		return this.descIndicador;
	}

	public void setDescIndicador(String descIndicador) {
		this.descIndicador = descIndicador;
	}

	@Column(name = "valor_indicador", nullable = false)
	public Long getValorIndicador() {
		return this.valorIndicador;
	}

	public void setValorIndicador(Long valorIndicador) {
		this.valorIndicador = valorIndicador;
	}
}
