package ar.com.celia.seguimiento_alumnos.domain;

// Generated 06/04/2014 19:30:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VwAlumnosActivos generated by hbm2java
 */
@Entity
@Table(name = "vw_alumno_materias", schema = "seguimiento_alumnos")
public class VwMaterias implements java.io.Serializable {

	private Long id;
	private Long userid;
	private String fullname;
	private String shortname;
	private String category;
	
	
	public VwMaterias() {
	}

	@Id
	@Column(name = "id", nullable = false)
	public Long getId() {
		return id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}	

	@Column(name = "userid", nullable = false)
	public Long getUserid() {
		return userid;
	}

	
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "fullname", nullable = false)
	public String getFullname() {
		return fullname;
	}
	
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "shortname", nullable = false)
	public String getShortname() {
		return shortname;
	}
	
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}
	
	@Column(name = "category", nullable = false)
	public String getCategory() {
		return category;
	}
		
	public void setCategory(String category) {
		this.category = category;
	}

}
