package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelDominio generated by hbm2java
 */
@Entity
@Table(name = "cel_alerta_enviada", catalog = "seguimiento_alumnos")
public class CelAlertaEnviada implements java.io.Serializable {

	private Long aleId;
	private String aleObjTipo;
	private Long aleObjId;
	private Long usrId;
	private String aleAlerta;
	private Date audFechaIns;

	public CelAlertaEnviada() {
	}

	

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ALE_ID", unique = true, nullable = false)
	public Long getAleId() {
		return aleId;
	}
	
	public void setAleId(Long aleId) {
		this.aleId = aleId;
	}



	@Column(name = "ALE_OBJ_TIPO", length = 250)
	public String getAleObjTipo() {
		return aleObjTipo;
	}



	public void setAleObjTipo(String aleObjTipo) {
		this.aleObjTipo = aleObjTipo;
	}



	@Column(name = "ALE_OBJ_ID")
	public Long getAleObjId() {
		return aleObjId;
	}



	public void setAleObjId(Long aleObjId) {
		this.aleObjId = aleObjId;
	}



	@Column(name = "USR_ID")
	public Long getUsrId() {
		return usrId;
	}



	public void setUsrId(Long usrId) {
		this.usrId = usrId;
	}



	@Column(name = "ALE_ALERTA", length = 250)
	public String getAleAlerta() {
		return aleAlerta;
	}



	public void setAleAlerta(String aleAlerta) {
		this.aleAlerta = aleAlerta;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "aud_fecha_ins")
	public Date getAudFechaIns() {
		return audFechaIns;
	}



	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	
	

}
