package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelBitacoraAlumnos generated by hbm2java
 */
@Entity
@Table(name = "cel_bitacora_alumnos", catalog = "seguimiento_alumnos")
public class CelBitacoraAlumnos implements java.io.Serializable {

	private Long btcId;
	private Long usrId;
	private String btcOrigenContacto;
	private String btcMotivoContacto;
	private String btcDescripcionContacto;
	private Date audFechaIns;
	private Date audFechaUpd;
	private String audUsrIns;
	private String audUsrUpd;

	public CelBitacoraAlumnos() {

	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "BTC_ID", unique = true, nullable = false)
	public Long getBtcId() {
		return btcId;
	}

	public void setBtcId(Long btcId) {
		this.btcId = btcId;
	}

	@Column(name = "USR_ID")
	public Long getUsrId() {
		return usrId;
	}

	public void setUsrId(Long usrId) {
		this.usrId = usrId;
	}

	@Column(name = "BTC_ORIGEN_CONTACTO", length = 100)
	public String getBtcOrigenContacto() {
		return btcOrigenContacto;
	}

	public void setBtcOrigenContacto(String btcOrigenContacto) {
		this.btcOrigenContacto = btcOrigenContacto;
	}

	@Column(name = "BTC_MOTIVO_CONTACTO", length = 100)
	public String getBtcMotivoContacto() {
		return btcMotivoContacto;
	}

	public void setBtcMotivoContacto(String btcMotivoContacto) {
		this.btcMotivoContacto = btcMotivoContacto;
	}

	@Column(name = "BTC_DESCRIPCION_CONTACTO", length = 100)
	public String getBtcDescripcionContacto() {
		return btcDescripcionContacto;
	}

	public void setBtcDescripcionContacto(String btcDescripcionContacto) {
		this.btcDescripcionContacto = btcDescripcionContacto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_INS", nullable = false, length = 19)
	public Date getAudFechaIns() {
		return this.audFechaIns;
	}

	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_UPD", nullable = false, length = 19)
	public Date getAudFechaUpd() {
		return this.audFechaUpd;
	}

	public void setAudFechaUpd(Date audFechaUpd) {
		this.audFechaUpd = audFechaUpd;
	}

	@Column(name = "AUD_USR_INS", nullable = false, length = 250)
	public String getAudUsrIns() {
		return this.audUsrIns;
	}

	public void setAudUsrIns(String audUsrIns) {
		this.audUsrIns = audUsrIns;
	}

	@Column(name = "AUD_USR_UPD", nullable = false, length = 250)
	public String getAudUsrUpd() {
		return this.audUsrUpd;
	}

	public void setAudUsrUpd(String audUsrUpd) {
		this.audUsrUpd = audUsrUpd;
	}

}