package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CelDominio generated by hbm2java
 */
@Entity
@Table(name = "cel_dominio", catalog = "seguimiento_alumnos")
public class CelDominio implements java.io.Serializable {

	private Long domId;
	private String domDominio;
	private String domClave;
	private short domEditable;
	private String domTexto;
	private short domOrden;

	public CelDominio() {
	}

	public CelDominio(String domClave, short domEditable, String domTexto,
			short domOrden) {
		this.domClave = domClave;
		this.domEditable = domEditable;
		this.domTexto = domTexto;
		this.domOrden = domOrden;
	}

	public CelDominio(String domDominio, String domClave, short domEditable,
			String domTexto, short domOrden) {
		this.domDominio = domDominio;
		this.domClave = domClave;
		this.domEditable = domEditable;
		this.domTexto = domTexto;
		this.domOrden = domOrden;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "DOM_ID", unique = true, nullable = false)
	public Long getDomId() {
		return this.domId;
	}

	public void setDomId(Long domId) {
		this.domId = domId;
	}

	@Column(name = "DOM_DOMINIO", length = 100)
	public String getDomDominio() {
		return this.domDominio;
	}

	public void setDomDominio(String domDominio) {
		this.domDominio = domDominio;
	}

	@Column(name = "DOM_CLAVE", nullable = false, length = 250)
	public String getDomClave() {
		return this.domClave;
	}

	public void setDomClave(String domClave) {
		this.domClave = domClave;
	}

	@Column(name = "DOM_EDITABLE", nullable = false)
	public short getDomEditable() {
		return this.domEditable;
	}

	public void setDomEditable(short domEditable) {
		this.domEditable = domEditable;
	}

	@Column(name = "DOM_TEXTO", nullable = false, length = 4000)
	public String getDomTexto() {
		return this.domTexto;
	}

	public void setDomTexto(String domTexto) {
		this.domTexto = domTexto;
	}

	@Column(name = "DOM_ORDEN", nullable = false)
	public short getDomOrden() {
		return this.domOrden;
	}

	public void setDomOrden(short domOrden) {
		this.domOrden = domOrden;
	}

}
