package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelIndicadorUsuarioEstado generated by hbm2java
 */
@Entity
@Table(name = "cel_indicador_usuario_estado", catalog = "seguimiento_alumnos")
public class CelIndicadorUsuarioEstado implements java.io.Serializable {

	private Long iueId;
	private CelIndicador celIndicador;
	private Date iueIgnorarHasta;
	private String iueObservaciones;
	private Date audFechaIns;
	private Date audFechaUpd;
	private String audUsrIns;
	private String audUsrUpd;

	public CelIndicadorUsuarioEstado() {
	}

	public CelIndicadorUsuarioEstado(CelIndicador celIndicador,
			Date iueIgnorarHasta, String iueObservaciones, Date audFechaIns,
			Date audFechaUpd, String audUsrIns, String audUsrUpd) {
		this.celIndicador = celIndicador;
		this.iueIgnorarHasta = iueIgnorarHasta;
		this.iueObservaciones = iueObservaciones;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "IUE_ID", unique = true, nullable = false)
	public Long getIueId() {
		return this.iueId;
	}

	public void setIueId(Long iueId) {
		this.iueId = iueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IND_ID", nullable = false)
	public CelIndicador getCelIndicador() {
		return this.celIndicador;
	}

	public void setCelIndicador(CelIndicador celIndicador) {
		this.celIndicador = celIndicador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IUE_IGNORAR_HASTA", nullable = false, length = 19)
	public Date getIueIgnorarHasta() {
		return this.iueIgnorarHasta;
	}

	public void setIueIgnorarHasta(Date iueIgnorarHasta) {
		this.iueIgnorarHasta = iueIgnorarHasta;
	}

	@Column(name = "IUE_OBSERVACIONES", nullable = false, length = 250)
	public String getIueObservaciones() {
		return this.iueObservaciones;
	}

	public void setIueObservaciones(String iueObservaciones) {
		this.iueObservaciones = iueObservaciones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_INS", nullable = false, length = 19)
	public Date getAudFechaIns() {
		return this.audFechaIns;
	}

	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_UPD", nullable = false, length = 19)
	public Date getAudFechaUpd() {
		return this.audFechaUpd;
	}

	public void setAudFechaUpd(Date audFechaUpd) {
		this.audFechaUpd = audFechaUpd;
	}

	@Column(name = "AUD_USR_INS", nullable = false, length = 250)
	public String getAudUsrIns() {
		return this.audUsrIns;
	}

	public void setAudUsrIns(String audUsrIns) {
		this.audUsrIns = audUsrIns;
	}

	@Column(name = "AUD_USR_UPD", nullable = false, length = 250)
	public String getAudUsrUpd() {
		return this.audUsrUpd;
	}

	public void setAudUsrUpd(String audUsrUpd) {
		this.audUsrUpd = audUsrUpd;
	}

}
