package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelIndicador generated by hbm2java
 */
@Entity
@Table(name = "cel_indicador", catalog = "seguimiento_alumnos")
public class CelIndicador implements java.io.Serializable {

	private Long indId;
	private String indNombre;
	private String indDescripcion;
	private Date audFechaIns;
	private Date audFechaUpd;
	private String audUsrIns;
	private String audUsrUpd;
	private Set celInteraccionCasoDetalles = new HashSet(0);
	private Set celIndicadorUsuarioEstados = new HashSet(0);

	public CelIndicador() {
	}

	public CelIndicador(String indNombre, String indDescripcion,
			Date audFechaIns, Date audFechaUpd, String audUsrIns,
			String audUsrUpd) {
		this.indNombre = indNombre;
		this.indDescripcion = indDescripcion;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
	}

	public CelIndicador(String indNombre, String indDescripcion,
			Date audFechaIns, Date audFechaUpd, String audUsrIns,
			String audUsrUpd, Set celInteraccionCasoDetalles,
			Set celIndicadorUsuarioEstados) {
		this.indNombre = indNombre;
		this.indDescripcion = indDescripcion;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
		this.celInteraccionCasoDetalles = celInteraccionCasoDetalles;
		this.celIndicadorUsuarioEstados = celIndicadorUsuarioEstados;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "IND_ID", unique = true, nullable = false)
	public Long getIndId() {
		return this.indId;
	}

	public void setIndId(Long indId) {
		this.indId = indId;
	}

	@Column(name = "IND_NOMBRE", nullable = false, length = 250)
	public String getIndNombre() {
		return this.indNombre;
	}

	public void setIndNombre(String indNombre) {
		this.indNombre = indNombre;
	}

	@Column(name = "IND_DESCRIPCION", nullable = false, length = 250)
	public String getIndDescripcion() {
		return this.indDescripcion;
	}

	public void setIndDescripcion(String indDescripcion) {
		this.indDescripcion = indDescripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_INS", nullable = false, length = 19)
	public Date getAudFechaIns() {
		return this.audFechaIns;
	}

	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_UPD", nullable = false, length = 19)
	public Date getAudFechaUpd() {
		return this.audFechaUpd;
	}

	public void setAudFechaUpd(Date audFechaUpd) {
		this.audFechaUpd = audFechaUpd;
	}

	@Column(name = "AUD_USR_INS", nullable = false, length = 250)
	public String getAudUsrIns() {
		return this.audUsrIns;
	}

	public void setAudUsrIns(String audUsrIns) {
		this.audUsrIns = audUsrIns;
	}

	@Column(name = "AUD_USR_UPD", nullable = false, length = 250)
	public String getAudUsrUpd() {
		return this.audUsrUpd;
	}

	public void setAudUsrUpd(String audUsrUpd) {
		this.audUsrUpd = audUsrUpd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "celIndicador")
	public Set getCelInteraccionCasoDetalles() {
		return this.celInteraccionCasoDetalles;
	}

	public void setCelInteraccionCasoDetalles(Set celInteraccionCasoDetalles) {
		this.celInteraccionCasoDetalles = celInteraccionCasoDetalles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "celIndicador")
	public Set getCelIndicadorUsuarioEstados() {
		return this.celIndicadorUsuarioEstados;
	}

	public void setCelIndicadorUsuarioEstados(Set celIndicadorUsuarioEstados) {
		this.celIndicadorUsuarioEstados = celIndicadorUsuarioEstados;
	}

}
