package ar.com.celia.seguimiento_alumnos.domain;

// Generated 20/04/2014 02:51:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CelInteraccionCasoDetalle generated by hbm2java
 */
@Entity
@Table(name = "cel_interaccion_caso_detalle", catalog = "seguimiento_alumnos")
public class CelInteraccionCasoDetalle implements java.io.Serializable {

	private Long icdId;
	private CelIndicador celIndicador;
	private String icdRtaTipo;
	private String icdObservaciones;
	private CelInteraccionCaso celInteraccionCaso;
	private Date audFechaIns;
	private Date audFechaUpd;
	private String audUsrIns;
	private String audUsrUpd;

	public CelInteraccionCasoDetalle() {
	}

	public CelInteraccionCasoDetalle(CelIndicador celIndicador,
			String icdRtaTipo, Date icdIgnorarHasta, String icdObservaciones,
			CelInteraccionCaso celInteraccionCaso, Date audFechaIns, Date audFechaUpd, String audUsrIns,
			String audUsrUpd) {
		this.celIndicador = celIndicador;
		this.icdRtaTipo = icdRtaTipo;
		this.icdObservaciones = icdObservaciones;
		this.celInteraccionCaso = celInteraccionCaso;
		this.audFechaIns = audFechaIns;
		this.audFechaUpd = audFechaUpd;
		this.audUsrIns = audUsrIns;
		this.audUsrUpd = audUsrUpd;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ICD_ID", unique = true, nullable = false)
	public Long getIcdId() {
		return this.icdId;
	}

	public void setIcdId(Long icdId) {
		this.icdId = icdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IND_ID", nullable = false)
	public CelIndicador getCelIndicador() {
		return this.celIndicador;
	}

	public void setCelIndicador(CelIndicador celIndicador) {
		this.celIndicador = celIndicador;
	}

	@Column(name = "ICD_RTA_TIPO", nullable = false, length = 250)
	public String getIcdRtaTipo() {
		return this.icdRtaTipo;
	}

	public void setIcdRtaTipo(String icdRtaTipo) {
		this.icdRtaTipo = icdRtaTipo;
	}

	@Column(name = "ICD_OBSERVACIONES", nullable = true, length = 250)
	public String getIcdObservaciones() {
		return this.icdObservaciones;
	}

	public void setIcdObservaciones(String icdObservaciones) {
		this.icdObservaciones = icdObservaciones;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAS_ID", nullable = false)
	public CelInteraccionCaso getCelInteraccionCaso() {
		return celInteraccionCaso;
	}

	public void setCelInteraccionCaso(CelInteraccionCaso celInteraccionCaso) {
		this.celInteraccionCaso = celInteraccionCaso;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_INS", nullable = false, length = 19)
	public Date getAudFechaIns() {
		return this.audFechaIns;
	}

	public void setAudFechaIns(Date audFechaIns) {
		this.audFechaIns = audFechaIns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_UPD", nullable = false, length = 19)
	public Date getAudFechaUpd() {
		return this.audFechaUpd;
	}

	public void setAudFechaUpd(Date audFechaUpd) {
		this.audFechaUpd = audFechaUpd;
	}

	@Column(name = "AUD_USR_INS", nullable = false, length = 250)
	public String getAudUsrIns() {
		return this.audUsrIns;
	}

	public void setAudUsrIns(String audUsrIns) {
		this.audUsrIns = audUsrIns;
	}

	@Column(name = "AUD_USR_UPD", nullable = false, length = 250)
	public String getAudUsrUpd() {
		return this.audUsrUpd;
	}

	public void setAudUsrUpd(String audUsrUpd) {
		this.audUsrUpd = audUsrUpd;
	}

}
