package ar.com.celia.core.domain;

// Generated 10-ene-2011 18:03:21 by Hibernate Tools 3.4.0.Beta1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CeliaError generated by hbm2java
 */
@Entity
@Table(name = "CELIA_ERROR")
public class CeliaError implements java.io.Serializable {

	private Long errId;
	private Long errOrigenId;
	private String errException;
	private String errMessage;
	private String errExtraInfo;
	private String errCause;
	private String errStackTrace;
	private String errNombreProyecto;
	private String errCliente;
	private String errAmbiente;
	private Date errFechaError;
	private Date errFechaEnvio;
	private Date errFechaRecibido;
	private String errHashId;

	public CeliaError() {
	}

	public CeliaError(Long errId) {
		this.errId = errId;
	}

	public CeliaError(Long errId, String errException, String errMessage,
			String errExtraInfo, String errCause, String errStackTrace,
			String errNombreProyecto, String errCliente, Date errFechaError,
			Date errFechaEnvio, Date errFechaRecibido) {
		this.errId = errId;
		this.errException = errException;
		this.errMessage = errMessage;
		this.errExtraInfo = errExtraInfo;
		this.errCause = errCause;
		this.errStackTrace = errStackTrace;
		this.errNombreProyecto = errNombreProyecto;
		this.errCliente = errCliente;
		this.errFechaError = errFechaError;
		this.errFechaEnvio = errFechaEnvio;
		this.errFechaRecibido = errFechaRecibido;
	}

	

	@Id @GeneratedValue(generator="sequence")
	@GenericGenerator(name="sequence", strategy = "sequence",
	parameters = {@Parameter(name="sequence", value="CELIA_ERROR_SEQ")})
	@Column(name = "ERR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getErrId() {
		return this.errId;
	}

	public void setErrId(Long errId) {
		this.errId = errId;
	}
	
	@Column(name = "ERR_ORIGEN_ID",precision = 22, scale = 0)
	public Long getErrOrigenId() {
		return errOrigenId;
	}
	
	public void setErrOrigenId(Long errOrigenId) {
		this.errOrigenId = errOrigenId;
	}

	@Column(name = "ERR_EXCEPTION", length = 600)
	public String getErrException() {
		return this.errException;
	}

	public void setErrException(String errException) {
		this.errException = errException;
	}

	@Column(name = "ERR_MESSAGE", length = 600)
	public String getErrMessage() {
		return this.errMessage;
	}

	public void setErrMessage(String errMessage) {
		this.errMessage = errMessage;
	}

	@Column(name = "ERR_EXTRA_INFO", length = 2000)
	public String getErrExtraInfo() {
		return this.errExtraInfo;
	}

	public void setErrExtraInfo(String errExtraInfo) {
		this.errExtraInfo = errExtraInfo;
	}

	@Column(name = "ERR_CAUSE", length = 600)
	public String getErrCause() {
		return this.errCause;
	}

	public void setErrCause(String errCause) {
		this.errCause = errCause;
	}

	@Column(name = "ERR_STACK_TRACE")
	public String getErrStackTrace() {
		return this.errStackTrace;
	}

	public void setErrStackTrace(String errStackTrace) {
		this.errStackTrace = errStackTrace;
	}

	@Column(name = "ERR_NOMBRE_PROYECTO", length = 100)
	public String getErrNombreProyecto() {
		return this.errNombreProyecto;
	}

	public void setErrNombreProyecto(String errNombreProyecto) {
		this.errNombreProyecto = errNombreProyecto;
	}

	@Column(name = "ERR_CLIENTE", length = 100)
	public String getErrCliente() {
		return this.errCliente;
	}

	public void setErrCliente(String errCliente) {
		this.errCliente = errCliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERR_FECHA_ERROR")
	public Date getErrFechaError() {
		return this.errFechaError;
	}

	public void setErrFechaError(Date errFechaError) {
		this.errFechaError = errFechaError;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERR_FECHA_ENVIO")
	public Date getErrFechaEnvio() {
		return this.errFechaEnvio;
	}

	public void setErrFechaEnvio(Date errFechaEnvio) {
		this.errFechaEnvio = errFechaEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ERR_FECHA_RECIBIDO")
	public Date getErrFechaRecibido() {
		return this.errFechaRecibido;
	}

	public void setErrFechaRecibido(Date errFechaRecibido) {
		this.errFechaRecibido = errFechaRecibido;
	}
	
	@Column(name = "ERR_AMBIENTE", length = 100)	
	public String getErrAmbiente() {
		return errAmbiente;
	}
	
	public void setErrAmbiente(String errAmbiente) {
		this.errAmbiente = errAmbiente;
	}

	@Column(name = "ERR_HASH_ID", length = 64)	
	public String setErrHashId() {
		return errHashId;
	}

	public void getErrHashId(String errHashId) {
		this.errHashId = errHashId;
	}
}